FROM centos:centos7
MAINTAINER Britt Gresham <britt@brittg.com>

ADD http://ftp.gnu.org/gnu/wget/wget-1.19.tar.xz /root/wget-1.19.tar.gz

RUN yum install -y tar make
RUN yum install -y which nano

WORKDIR /root/
